# Pandas: Datasets en 2D

In [99]:
import pandas as pd
import numpy as np

## Dataframes
### Datframe directo

In [100]:
df = pd.DataFrame([[420, 50], [380,40], [390, 45]],
                  index=['Alex', 'Diana', 'Manuel'],
                  columns=['calories', 'duration'])
print(df)

        calories  duration
Alex         420        50
Diana        380        40
Manuel       390        45

### Diccionarios (Matrices por columnas)

In [101]:
data = {
  "name": ['Alex', 'Diana', 'Manuel'],
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

print(type(data))

df = pd.DataFrame(data)
df.set_index('name', inplace=True)

print(type(df))

print(df)

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
        calories  duration
name
Alex         420        50
Diana        380        40
Manuel       390        45

### Listas (matrices por filas)

In [102]:
data = [["name", "calories", "duration"], ['Alex', 420, 50], ['Diana', 380,40], ['Alex', 390, 45]]

print(type(data))

df = pd.DataFrame(data[1:], columns=data[0])
df.set_index('name', inplace=True)

print(type(df))

print(df)

<class 'list'>
<class 'pandas.core.frame.DataFrame'>
       calories  duration
name
Alex        420        50
Diana       380        40
Alex        390        45

## Locate

In [103]:
print('loc para ubicar por nombre del indice')
print(df.loc["Alex"])
print('-------------------------')
print(df.loc["Alex",'calories'])
print('-------------------------')
print('loci para ubicar por indice')
print(df.iloc[1])
print('-------------------------')
print(df.iloc[[0, 1]])
print('Asignar nuevo valor a una celda')
df.loc["Diana", 'duration'] = 15
print(df)
print('Asignar nuevo valor a varias celdas bajo una regla')
df["duration"] = df["duration"].where(df["duration"] >= 16, 16)
print(df)
print('Eliminar columnas bajo una condicion')
df = df.drop(df[df['duration'] <= 16].index)
print(df)

loc para ubicar por nombre del indice
      calories  duration
name
Alex       420        50
Alex       390        45
-------------------------
name
Alex    420
Alex    390
Name: calories, dtype: int64
-------------------------
loci para ubicar por indice
calories    380
duration     40
Name: Diana, dtype: int64
-------------------------
       calories  duration
name
Alex        420        50
Diana       380        40
Asignar nuevo valor a una celda
       calories  duration
name
Alex        420        50
Diana       380        15
Alex        390        45
Asignar nuevo valor a varias celdas bajo una regla
       calories  duration
name
Alex        420        50
Diana       380        16
Alex        390        45
Eliminar columnas bajo una condicion
      calories  duration
name
Alex       420        50
Alex       390        45

## CSV

In [104]:
df = pd.read_csv('data.csv')

print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

## Limpieza de datos

### Celdas vacias (dropna)

In [105]:
new_df = df.dropna()
print(new_df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### Fillna & inplace=True

In [106]:
print('Remplazar solo en una coumna')
df["Calories"].fillna(130, inplace = True)
print(df.to_string())

Remplazar solo en una coumna
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     130.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132     130.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137     130.0
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125     130.0
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127     130.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

C:\Users\grego\AppData\Local\Temp\ipykernel_2984\2186614178.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Calories"].fillna(130, inplace = True)

In [107]:
print('Remplazar todo')
df.fillna(0, inplace = True)
print(df)

Remplazar todo
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

### Formato

In [108]:
df = pd.read_csv('bquxjob_320d31a1_19029f73ed9_chicago_crime.csv')
print(df)
df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.date
print(df)

       unique_key case_number                            date  \
0        10475652    HZ215006  2016-04-06 12:18:00.000000 UTC
1         7764491    HS572617  2010-10-17 05:00:00.000000 UTC
2         3632575    HK724678  2003-09-01 11:00:00.000000 UTC
3         5997711    HN764730  2007-12-17 07:00:00.000000 UTC
4         1883360     G723783  2001-12-03 12:35:11.000000 UTC
...           ...         ...                             ...
30164    10102355    HY291143  2015-06-07 04:18:00.000000 UTC
30165     9155669    HW301401  2013-06-02 02:00:00.000000 UTC
30166     2732358    HJ338618  2003-05-02 11:50:00.000000 UTC
30167    11508069    JB516849  2018-11-15 11:05:00.000000 UTC
30168     2761035    HJ394254  2003-05-29 12:55:00.000000 UTC

                       block  iucr                primary_type  \
0        015XX N LARAMIE AVE  4625               OTHER OFFENSE
1         051XX W ALTGELD ST  0520                     ASSAULT
2       022XX N LAVERGNE AVE  1753  OFFENSE INVOLVING CHILDREN
3          052XX W NORTH AVE  1120          DECEPTIVE PRACTICE
4       019XX N FAIRFIELD AV  2022                   NARCOTICS
...                      ...   ...                         ...
30164  015XX N MILWAUKEE AVE  1305             CRIMINAL DAMAGE
30165     026XX N ELSTON AVE  1152          DECEPTIVE PRACTICE
30166      016XX W NORTH AVE  2170                   NARCOTICS
30167      0000X S LOTUS AVE  1822                   NARCOTICS
30168      050XX W FULTON ST  1120          DECEPTIVE PRACTICE

                          description     location_description  arrest  \
0                    PAROLE VIOLATION                   STREET    True
1      AGGRAVATED:KNIFE/CUTTING INSTR  RESIDENCE PORCH/HALLWAY    True
2       SEX ASSLT OF CHILD BY FAM MBR                RESIDENCE   False
3                             FORGERY        CURRENCY EXCHANGE   False
4                       POSS: COCAINE                   STREET    True
...                               ...                      ...     ...
30164             CRIMINAL DEFACEMENT                    ALLEY    True
30165           ILLEGAL USE CASH CARD                    OTHER   False
30166    POSSESSION OF DRUG EQUIPMENT                   STREET    True
30167   MANU/DEL:CANNABIS OVER 10 GMS                   STREET    True
30168                         FORGERY                APARTMENT   False

       domestic  ...  ward  community_area  fbi_code  x_coordinate  \
0         False  ...  37.0            25.0        26     1141426.0
1          True  ...  31.0            19.0       04A     1141604.0
2         False  ...  31.0            19.0        02     1142693.0
3         False  ...  37.0            25.0        10     1141381.0
4         False  ...   NaN             NaN        18     1157694.0
...         ...  ...   ...             ...       ...           ...
30164     False  ...   1.0            24.0        14     1163416.0
30165     False  ...   1.0            22.0        11     1160965.0
30166     False  ...   1.0            24.0        18     1165350.0
30167     False  ...  29.0            25.0        18     1139888.0
30168     False  ...  28.0            25.0        10     1142730.0

      y_coordinate  year                      updated_on   latitude  \
0        1909653.0  2016  2018-02-10 03:50:01.000000 UTC  41.908162
1        1916147.0  2010  2018-02-10 03:50:01.000000 UTC  41.925979
2        1914374.0  2003  2018-02-28 03:56:25.000000 UTC  41.921093
3        1910140.0  2007  2018-02-28 03:56:25.000000 UTC  41.909499
4        1912542.0  2001  2015-08-17 03:03:40.000000 UTC  41.915773
...            ...   ...                             ...        ...
30164    1910072.0  2015  2018-02-10 03:50:01.000000 UTC  41.908877
30165    1917567.0  2013  2018-02-10 03:50:01.000000 UTC  41.929495
30166    1910724.0  2003  2018-02-28 03:56:25.000000 UTC  41.910625
30167    1899390.0  2018  2018-11-22 04:08:52.000000 UTC  41.880027
30168    1901473.0  2003  2018-02-28 03:56:25.000000 UTC  41.885691

       longitude                       location
0     -87.755913  (41.908161602, -87.755912898)
1     -87.755098   (41.92597855, -87.755098164)
2     -87.751141  (41.921093034, -87.751140802)
3     -87.756066  (41.909498816, -87.756066167)
4     -87.696073  (41.915773193, -87.696073389)
...          ...                            ...
30164 -87.675121  (41.908876749, -87.675120839)
30165 -87.683916  (41.929494816, -87.683916158)
30166 -87.667998  (41.910624936, -87.667997673)
30167 -87.761814  (41.880026947, -87.761813935)
30168 -87.751326  (41.885690546, -87.751326451)

[30169 rows x 22 columns]
       unique_key case_number        date                  block  iucr  \
0        10475652    HZ215006  2016-04-06    015XX N LARAMIE AVE  4625
1         7764491    HS572617  2010-10-17     051XX W ALTGELD ST  0520
2         3632575    HK724678  2003-09-01   022XX N LAVERGNE AVE  1753
3         5997711    HN764730  2007-12-17      052XX W NORTH AVE  1120
4         1883360     G723783  2001-12-03   019XX N FAIRFIELD AV  2022
...           ...         ...         ...                    ...   ...
30164    10102355    HY291143  2015-06-07  015XX N MILWAUKEE AVE  1305
30165     9155669    HW301401  2013-06-02     026XX N ELSTON AVE  1152
30166     2732358    HJ338618  2003-05-02      016XX W NORTH AVE  2170
30167    11508069    JB516849  2018-11-15      0000X S LOTUS AVE  1822
30168     2761035    HJ394254  2003-05-29      050XX W FULTON ST  1120

                     primary_type                     description  \
0                   OTHER OFFENSE                PAROLE VIOLATION
1                         ASSAULT  AGGRAVATED:KNIFE/CUTTING INSTR
2      OFFENSE INVOLVING CHILDREN   SEX ASSLT OF CHILD BY FAM MBR
3              DECEPTIVE PRACTICE                         FORGERY
4                       NARCOTICS                   POSS: COCAINE
...                           ...                             ...
30164             CRIMINAL DAMAGE             CRIMINAL DEFACEMENT
30165          DECEPTIVE PRACTICE           ILLEGAL USE CASH CARD
30166                   NARCOTICS    POSSESSION OF DRUG EQUIPMENT
30167                   NARCOTICS   MANU/DEL:CANNABIS OVER 10 GMS
30168          DECEPTIVE PRACTICE                         FORGERY

          location_description  arrest  domestic  ...  ward  community_area  \
0                       STREET    True     False  ...  37.0            25.0
1      RESIDENCE PORCH/HALLWAY    True      True  ...  31.0            19.0
2                    RESIDENCE   False     False  ...  31.0            19.0
3            CURRENCY EXCHANGE   False     False  ...  37.0            25.0
4                       STREET    True     False  ...   NaN             NaN
...                        ...     ...       ...  ...   ...             ...
30164                    ALLEY    True     False  ...   1.0            24.0
30165                    OTHER   False     False  ...   1.0            22.0
30166                   STREET    True     False  ...   1.0            24.0
30167                   STREET    True     False  ...  29.0            25.0
30168                APARTMENT   False     False  ...  28.0            25.0

       fbi_code  x_coordinate y_coordinate  year  \
0            26     1141426.0    1909653.0  2016
1           04A     1141604.0    1916147.0  2010
2            02     1142693.0    1914374.0  2003
3            10     1141381.0    1910140.0  2007
4            18     1157694.0    1912542.0  2001
...         ...           ...          ...   ...
30164        14     1163416.0    1910072.0  2015
30165        11     1160965.0    1917567.0  2013
30166        18     1165350.0    1910724.0  2003
30167        18     1139888.0    1899390.0  2018
30168        10     1142730.0    1901473.0  2003

                           updated_on   latitude  longitude  \
0      2018-02-10 03:50:01.000000 UTC  41.908162 -87.755913
1      2018-02-10 03:50:01.000000 UTC  41.925979 -87.755098
2      2018-02-28 03:56:25.000000 UTC  41.921093 -87.751141
3      2018-02-28 03:56:25.000000 UTC  41.909499 -87.756066
4      2015-08-17 03:03:40.000000 UTC  41.915773 -87.696073
...                               ...        ...        ...
30164  2018-02-10 03:50:01.000000 UTC  41.908877 -87.675121
30165  2018-02-10 03:50:01.000000 UTC  41.929495 -87.683916
30166  2018-02-28 03:56:25.000000 UTC  41.910625 -87.667998
30167  2018-11-22 04:08:52.000000 UTC  41.880027 -87.761814
30168  2018-02-28 03:56:25.000000 UTC  41.885691 -87.751326

                            location
0      (41.908161602, -87.755912898)
1       (41.92597855, -87.755098164)
2      (41.921093034, -87.751140802)
3      (41.909498816, -87.756066167)
4      (41.915773193, -87.696073389)
...                              ...
30164  (41.908876749, -87.675120839)
30165  (41.929494816, -87.683916158)
30166  (41.910624936, -87.667997673)
30167  (41.880026947, -87.761813935)
30168  (41.885690546, -87.751326451)

[30169 rows x 22 columns]

## Duplicados

In [110]:
print(df.duplicated())
df.drop_duplicates(inplace = True)
print(df)

0        False
1        False
2        False
3        False
4        False
         ...
30164    False
30165    False
30166    False
30167    False
30168    False
Length: 30169, dtype: bool
       unique_key case_number        date                  block  iucr  \
0        10475652    HZ215006  2016-04-06    015XX N LARAMIE AVE  4625
1         7764491    HS572617  2010-10-17     051XX W ALTGELD ST  0520
2         3632575    HK724678  2003-09-01   022XX N LAVERGNE AVE  1753
3         5997711    HN764730  2007-12-17      052XX W NORTH AVE  1120
4         1883360     G723783  2001-12-03   019XX N FAIRFIELD AV  2022
...           ...         ...         ...                    ...   ...
30164    10102355    HY291143  2015-06-07  015XX N MILWAUKEE AVE  1305
30165     9155669    HW301401  2013-06-02     026XX N ELSTON AVE  1152
30166     2732358    HJ338618  2003-05-02      016XX W NORTH AVE  2170
30167    11508069    JB516849  2018-11-15      0000X S LOTUS AVE  1822
30168     2761035    HJ394254  2003-05-29      050XX W FULTON ST  1120

                     primary_type                     description  \
0                   OTHER OFFENSE                PAROLE VIOLATION
1                         ASSAULT  AGGRAVATED:KNIFE/CUTTING INSTR
2      OFFENSE INVOLVING CHILDREN   SEX ASSLT OF CHILD BY FAM MBR
3              DECEPTIVE PRACTICE                         FORGERY
4                       NARCOTICS                   POSS: COCAINE
...                           ...                             ...
30164             CRIMINAL DAMAGE             CRIMINAL DEFACEMENT
30165          DECEPTIVE PRACTICE           ILLEGAL USE CASH CARD
30166                   NARCOTICS    POSSESSION OF DRUG EQUIPMENT
30167                   NARCOTICS   MANU/DEL:CANNABIS OVER 10 GMS
30168          DECEPTIVE PRACTICE                         FORGERY

          location_description  arrest  domestic  ...  ward  community_area  \
0                       STREET    True     False  ...  37.0            25.0
1      RESIDENCE PORCH/HALLWAY    True      True  ...  31.0            19.0
2                    RESIDENCE   False     False  ...  31.0            19.0
3            CURRENCY EXCHANGE   False     False  ...  37.0            25.0
4                       STREET    True     False  ...   NaN             NaN
...                        ...     ...       ...  ...   ...             ...
30164                    ALLEY    True     False  ...   1.0            24.0
30165                    OTHER   False     False  ...   1.0            22.0
30166                   STREET    True     False  ...   1.0            24.0
30167                   STREET    True     False  ...  29.0            25.0
30168                APARTMENT   False     False  ...  28.0            25.0

       fbi_code  x_coordinate y_coordinate  year  \
0            26     1141426.0    1909653.0  2016
1           04A     1141604.0    1916147.0  2010
2            02     1142693.0    1914374.0  2003
3            10     1141381.0    1910140.0  2007
4            18     1157694.0    1912542.0  2001
...         ...           ...          ...   ...
30164        14     1163416.0    1910072.0  2015
30165        11     1160965.0    1917567.0  2013
30166        18     1165350.0    1910724.0  2003
30167        18     1139888.0    1899390.0  2018
30168        10     1142730.0    1901473.0  2003

                           updated_on   latitude  longitude  \
0      2018-02-10 03:50:01.000000 UTC  41.908162 -87.755913
1      2018-02-10 03:50:01.000000 UTC  41.925979 -87.755098
2      2018-02-28 03:56:25.000000 UTC  41.921093 -87.751141
3      2018-02-28 03:56:25.000000 UTC  41.909499 -87.756066
4      2015-08-17 03:03:40.000000 UTC  41.915773 -87.696073
...                               ...        ...        ...
30164  2018-02-10 03:50:01.000000 UTC  41.908877 -87.675121
30165  2018-02-10 03:50:01.000000 UTC  41.929495 -87.683916
30166  2018-02-28 03:56:25.000000 UTC  41.910625 -87.667998
30167  2018-11-22 04:08:52.000000 UTC  41.880027 -87.761814
30168  2018-02-28 03:56:25.000000 UTC  41.885691 -87.751326

                            location
0      (41.908161602, -87.755912898)
1       (41.92597855, -87.755098164)
2      (41.921093034, -87.751140802)
3      (41.909498816, -87.756066167)
4      (41.915773193, -87.696073389)
...                              ...
30164  (41.908876749, -87.675120839)
30165  (41.929494816, -87.683916158)
30166  (41.910624936, -87.667997673)
30167  (41.880026947, -87.761813935)
30168  (41.885690546, -87.751326451)

[30169 rows x 22 columns]